### ISSUE TITLE
Spells category not appearing for tokens with only "always prepared" spells.

### ISSUE THREAD

**Issue by Battenhatch** [espositos/fvtt-tokenactionhud#240]
HUD is now appearing for all characters, which is great.
One little corner remains, though - the Spells category doesn't seem to appear if a character has only "Always Prepared" spells, like a Bard, Sorcerer or Ranger - this is true for me in two different campaigns.

**Comment by Battenhatch** [comment]
Oh, and the system doesn't throw any error messages regarding this.

**Comment by p-becker** [comment]
Which fvtt and module version are you using? Possibly related to #239

**Comment by espositos** [comment]
Yes, the prepared notation might have moved. I will look at it this evening.

**Comment by espositos** [comment]
Because I'm not sure how multiclassing interacts with this, I'm hesitant to use this option over setting spells to 'always prepared' per the option in the spell configuration.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/14127543/120227343-428efb80-c249-11eb-9d4b-d49acf074d5e.png">

If you have a multiclass sorcerer/wizard, I assume that not every spell should be 'always prepared'? Otherwise you could have a Sor 1/Wiz 19 who has an entire library of spells that are always prepared, even though they only have two first level Sorc slots. If it's a complex interaction between preparedness and class, I don't want to show all spells simply because that actor has a particular class.

However, I'd be happy to hear arguments.

**Comment by espositos** [comment]
Regarding 'always prepared' spells not showing, this was a bug that I think I've fixed in the latest patch, but it needs to be set explicitly on the spell. Again, if it's not working for you and you're using the latest patch, let me know.

**Comment by p-becker** [comment]
Good points. Using that menu seems fine with me so I'll abort the PR.
You seem to have fixed the initial issue here, can't reproduce it :)

**Comment by Battenhatch** [comment]
"Spells" still not showing at my end with latest update, if spells are "Always Prepared".

**Comment by espositos** [comment]
*shakes fist at sky* okay, I'll look at it

**Comment by Battenhatch** [comment]
The problem turns out to not what I thought - it's not wether it's "always prepared" or not - it about the "prepared" checkbox next to the field where the preparedness level is set. This need to be checked for at spell to be included in the "Spells" category. The characters wher the category didn't show had none of these boxes checked.
![checkbox](https://user-images.githubusercontent.com/24476876/120371112-a54dc900-c315-11eb-9599-60d50580b50d.png)

**Comment by Battenhatch** [comment]
And no, it wasn't even that - it was a d*** module settings issue, and thus not an issue - well, you learn something new every day :)
